### ISSUE TITLE
Local-only Ground collection freezes browser on page load

### ISSUE THREAD

**Issue by gwendall** [Meteor-Community-Packages/ground-db#89] opened 2015-03-30 23:23 UTC
I have a local-only Ground collection (containing about a thousand docs) with a template rendering its documents.

``` javascript
Collection = new Ground.Collection("xxx", { connection: null });
Template.list.helpers({
  items: function() {
    return Collection.find({}, { limit: 10 });
  }
});
```

Whenever I load the page, the browser freezes (CPU usage goes to 100%) for a few seconds, then things get back to normal and the elements get displayed. Is that a known bug? How could I circumvent that?

**Comment by raix** [comment] 2015-03-31 06:27
Please provide a minimalistic reproduction I'll take a look at it.

**Comment by gwendall** [comment] 2015-04-01 14:20
Will do. I assume it comes from there. https://github.com/GroundMeteor/db/blob/connection-driver/groundDB.client.js#L454.
Bulk inserting many docs with vanilla Collection.insert() is not the most efficient way to do that. 

Please check those discussions:
- https://groups.google.com/forum/#!topic/meteor-talk/9qtZQiKlmiQ
- https://github.com/meteor/meteor/issues/1255

**Comment by raix** [comment] 2015-04-01 14:43
The most efficient way would be to set the in memory map directly. Then iterate over it marking things as offline only for later comparison with actual subscribed data.

That said - if the app is freezing it could be due to large data. We could use a small package I wrote a month or two ago `dispatch:kernel`

And use the `Kernel.each` instead - this will defer and respect frame rates, in other words it can't block the UI.

```js
// _groundUtil.each(_checkDocs.call(self, docs || {} ), function(doc) {
Kernel.each(_checkDocs.call(self, docs || {} ), function(doc) {
// Do the loading...
}).then(function() {
    // Setting database loaded, this allows minimongo to be saved into local
    self._databaseLoaded = true;
});
```

https://atmospherejs.com/dispatch/kernel

If that doesn't help I think we should get started on `ground:store` - at the moment theres only a `ground:localstorage` adapter - but we should have one for cordova and one for indexeddb *(I actually just want one package that gives the namespaced async api for the best possible storage available on the client - so far these are abstracted into adapters)*

**Comment by gwendall** [comment] 2015-04-02 10:00
I confirm that the initial load of a large nb of docs from localstorage to collections is what blocks the UI. I managed to run it without blocking by using an async each loop (see https://github.com/gwendall/db/commit/5d3b07972dd0617222b79cab6f270466523b19ef). For the record, i tried ```Kernel.each``` but that was still blocking. 
And +1 for ```ground:store```, using indexeddb whenever possible would be great.

**Comment by gwendall** [comment] 2015-04-02 10:00
I confirm that the initial load of a large nb of docs from localstorage to collections is what blocks the UI. I managed to run it without blocking by using an async each loop (see https://github.com/gwendall/db/commit/5d3b07972dd0617222b79cab6f270466523b19ef). For the record, i tried ```Kernel.each``` but that was still blocking. 
And +1 for ```ground:store```, using indexeddb whenever possible would be great.

**Comment by gwendall** [comment] 2015-04-02 10:00
I confirm that the initial load of a large nb of docs from localstorage to collections is what blocks the UI. I managed to run it without blocking by using an async each loop (see https://github.com/gwendall/db/commit/5d3b07972dd0617222b79cab6f270466523b19ef). For the record, i tried ```Kernel.each``` but that was still blocking. 
And +1 for ```ground:store```, using indexeddb whenever possible would be great.

**Comment by raix** [comment] 2015-04-02 10:02
super,
odd that `Kernel.each` is blocking - it shouldn't be able to - could be that it's actually localstorage doing the real blocking

**Comment by gwendall** [comment] 2015-04-02 10:12
It starts blocking after ```storage.getItem``` returns so it really is a loop issue. Strange for Kernel, haven't had time to dig into it. For ```ground:store```, why not simply use localForage? (And btw, I saw your published a package for it!)

**Comment by raix** [comment] 2015-04-02 11:01
Ok, low on time myself,

localforage doesn't support namespacing of storage and events... So I decided to do my own meteoric implementation.

**Comment by nicolsondsouza** [comment] 2015-04-08 13:12
Hey, I know this issue,
I believe, when I was dealing with phonegap apps,
my app use to get stuck,
because ground db was storing entire DB in localstorage,
on every update.

**Comment by raix** [comment] 2015-04-08 13:20
@nicolsondsouza yep, on small data sizes it doesn't matter but on larger sizes it becomes a problem mainly because localstorage is blocking the event loop. The localstorage storage adapter is prepared to do single document updates, but it's not implemented in ground:db yet - We also need more storage adapters :)

**Comment by nicolsondsouza** [comment] 2015-04-08 13:27
Because of this problem, 
I created my own Local storage,
which act similar to groundDB,
but not as good as groundDB,
yup but does the trick,

It is call on startup, to restore data,
and it is called on when session is about to end to store the data,
this way, the problem is fixed.

**Comment by raix** [comment] 2015-04-08 14:05
@nicolsondsouza I'm sorry to hear - we could have implemented storage pr. document instead,

**Comment by StorytellerCZ** [comment] 2024-06-17 17:47
Kernel was implemented a while ago. Closing this.

**Closed by StorytellerCZ** 2024-06-17 17:47 UTC
