### ISSUE TITLE
[question]usage with meteor 1.3

### ISSUE THREAD

**Issue by dagatsoin** [Meteor-Community-Packages/ground-db#153] opened 2016-02-20 13:19 UTC
Hi,
I just found your package while looking around to have a CouchDB like behavior with sync offline/online and persistant data. I will use Cordova and Meteor 1.3 for my project.

Do you know any issues to use the alpha version of GroundDB with 1.3?

**Comment by ecerroni** [comment] 2016-02-20 15:28
I was wondering about the same. Looking forward to get an answer here.

**Comment by dagatsoin** [comment] 2016-02-22 18:31
Looking to the alpha 1.0 branch, there is no update since August '14? Is this project frozen?

**Comment by dagatsoin** [comment] 2016-02-22 19:43
I simply tried:
```
var list = new Meteor.Collection(null);
var groundList = new Ground.Collection(list, 'list');
```
I got:
`Ground.Collection requires a collection name [missing-name]`

So I think it is not compatible yet.

**Comment by ecerroni** [comment] 2016-02-22 19:49
Try
var list = new Mongo.Collection(null);

**Comment by dagatsoin** [comment] 2016-02-22 20:18
Yep, it is what I did, I pasted the wrong part.

Plus, the package removes `standard-minimifiers.js` and as the last commit on the alpha branch was in November I don't think the library is up to date.

So for now, it is not usable in 1.3.

**Comment by ecerroni** [comment] 2016-02-22 20:21
Too bad. It's a package I used for a mobile app with great success.

It's perfect for offline mobile apps. I hope the library will eventually be updated for Meteor 1.3

**Comment by dagatsoin** [comment] 2016-02-22 20:32
I hope so much too! And I will attempt a nasty ping to @raix to know its plan about this :)

**Comment by raix** [comment] 2016-02-22 21:01
Hi guys - working on it :)

**Comment by dagatsoin** [comment] 2016-02-22 21:09
<3

**Comment by ecerroni** [comment] 2016-02-22 21:47
Great! :)

**Comment by marbemac** [comment] 2016-03-09 18:27
Seems to work fine in 1.3 for us:

```js
new Ground.Collection('grounded_entries', { connection: null })
```

**Comment by veeramarni** [comment] 2016-03-15 15:58
Is the issue fixed in Meteor 1.3 version?

**Comment by dagatsoin** [comment] 2016-03-29 09:14
Hi @raix do you need some help for the next grounddb version? I don't know if I have the level for collaborating on this but if you have got clear task todo I can look at it.

**Comment by raix** [comment] 2016-04-06 05:30
Hey guys,

cc.: @dagatsoin

Take a look at `2.0.0-alpha.1` branch https://github.com/GroundMeteor/db/tree/grounddb-caching-2016 - review / feedback is welcome

I've decoupled the new ground db to be a pure caching db (at least for now) - The major reason is that it's more important to have more control of the cached data. Second reason is than you might want to swap out the source at some point.

Migration would probably look something like:
```js
  // current "connection-driver"
  var foo = Ground.Collection('bar', {
    cleanupLocalData: false, // Manually trigger cleanup
  });

  Meteor.subscribe('bar', () => {
    foo.removeLocalOnly(); // Match grounded data with subscription
  });
```

```js
  // current "ground db II"
  const bar = new Mongo.Collection('bar');
  const foo = new Ground.Collection('foo');
  foo.observeSource(bar.find()); // Cache bar or a subset of bar

  Meteor.subscribe('bar', () => {
    foo.keep(bar.find()); // Match grounded data with subscription or a subset
  });
```

Again the GroundDB II does not cache/resume outstanding method calls or try to be clever about things - but it supports localforage (localstorage/indexeddb/websql and SQLite on cordova) so it's non blocking.

Comparison with approximate 2.000 documents:
Current ground db: (Notice the white screen at first while ground db is blocking)
![grounddb-old-blocking](https://cloud.githubusercontent.com/assets/1136718/14306583/c05cb5cc-fbc8-11e5-82dd-436e5330c452.gif)

Ground db v2:
![grounddb-new-nonblocking](https://cloud.githubusercontent.com/assets/1136718/14306589/cc27f9f2-fbc8-11e5-9de4-f3bb954998e1.gif)

**Comment by dagatsoin** [comment] 2016-04-06 07:25
Love it!
I need to finish a project first this week and I will jump into it. This new version seems very decoupled, smart move!
I already use SQLi through Mapbox offline, so I may be able to reuse it with ground db instead of having two different persistant DBs.
Can't wait to install it!

**Comment by KoenLav** [comment] 2016-04-06 09:15
"Again the GroundDB II does not cache/resume outstanding method calls or try to be clever about things"

Does this mean it will no longer forward collection changes made when the application is offline?

**Comment by raix** [comment] 2016-04-06 09:31
@KoenLav it's a behaviour that can be added later on or by a package, for now I want to keep ground:db II simple and decoulped from the source - eg. you could populate the data from other sources.

Resuming out standing method calls are not without issues - one is the missing callback, we cant resume callback instances which makes the code feel odd.

There might be use cases for it - but I'd rather tackle it from a different approach: if the server wants to update the local data you might want to check if the client data is newer than the server (eg. a committed change not received correctly by the server) - in this case theres a conflict, so having the option to opt in a conflict handler will allow the client to catch that send a new commit to the server or even ask the user if it cannot be resolve automatically.

I also want to allow the concept of "WIP" eg. allowing the user to work on stuff without committing it to the server.

**Comment by KoenLav** [comment] 2016-04-06 09:37
I understand.

I did however run some tests and it does seem that changes made to collections while the client is offline are later reflected on other clients after the first client regains connectivity.

Do note: I did not modify any of our code, I simply make use of the notation:
    Meteor.subscribe('products')
    Ground.Collection(Products)
and it works.

Is this intended behavior with the 2.0 alpha branch then?

**Comment by raix** [comment] 2016-04-06 10:06
@KoenLav yeah,

V1 listens to the localstorage events making updates in one tab also update in other tabs even if the app is offline, it's a feature that might be implemented in V2 later - since it can be useful eg for pure offline collections etc. *(more or less a refactor of [this chuck](https://github.com/GroundMeteor/db/blob/connection-driver/groundDB.client.js#L981-L993))*

The outstanding method resume is part of Meteor - but will not be persisted in V2 *([basically this chuck that resumed methods](https://github.com/GroundMeteor/db/blob/connection-driver/groundDB.client.js#L576-L871))*

**Comment by KoenLav** [comment] 2016-04-06 10:11
I see, I was just a little worried that simple changes to a collection would not be 'resumed' after reconnecting with the server (e.g. it could leave clients out of sync at some point). But this does not seem to be the case, as I pointed out above.

Initially not supporting resuming outstanding methods seems like a smart thing to do.

**Comment by mrlowe** [comment] 2016-04-25 14:13
Hi @raix, I'm just showing up to the Meteor+GroundDB party and seeing this note about your next version, specifically the bit about no longer resuming outstanding methods. It's a little confusing to me, though. Suppose I want to insert an object into a collection. Can that be done securely without using a server method?

**Comment by dagatsoin** [comment] 2016-05-01 18:31
@raix I am ready to dive in groundb. Question: how to manage storage system? I use Cordova and will surely use the SQLite plugin. So how to make sure that grounddb will use SQLite?

**Comment by dagatsoin** [comment] 2016-05-01 18:52
And which SQLite plugin must we use? https://github.com/litehelpers/Cordova-sqlite-storage or https://github.com/nolanlawson/cordova-plugin-sqlite-2?

**Comment by atulmy** [comment] 2016-05-01 19:44
@raix I'm building an app for a clinic and would require data offline. Its on Meteor 1.3. Which version should I go ahead with? Ground DB 1 or if 2 alpha is usable on production as well? Any help or alternatives would be useful!

**Comment by raix** [comment] 2016-05-02 07:46
@dagatsoin the `2.0.0-rc.3` uses localforage - so you can install the SQLite localforage plugin and configure a localforage storage manually:
```js
import localforage from 'localforage';
import Ground from 'meteor/ground:db';

const fooStorageAdapter = localforage.createInstance({
  driver: window.cordovaSQLiteDriver._driver, // Not tested - depends on the plugin
  name: 'foo',
  version: 1.0,
});
const foo = new Ground.Collection('foo', {
  storageAdapter: fooStorageAdapter,
});

foo.observeSource(bar.find());
```

@atulmy on Meteor 1.3 I would use `2.0.0-rc.3` - the old version might break

**Comment by dagatsoin** [comment] 2016-05-06 07:38
hi @raix I don't get how to install the `2.0.0-rc.3. Currently I have downloaded the last commit in /packages/grounddb then I did `meteor add ground:db@2.0.0-rc.3`

The terminal displayed:
```
Changes to your project's package version selections:
                                              
dispatch:kernel                   added, version 0.0.6
dispatch:request-animation-frame  added, version 0.0.1
ground:db                         added, version 2.0.0-rc.3
ground:servertime                 added, version 2.0.0
raix:eventemitter                 added, version 0.1.3
raix:eventstate                   added, version 0.0.4

```
So I guess it is OK. But When I try to import it with `import Ground from 'meteor/ground:db';` Webstorm does not find the path.

**Comment by dagatsoin** [comment] 2016-05-06 11:45
and import `localforage from 'localforage';` is also marked in red.
`import localforage from 'localforage-cordovasqlitedriver/src';`is not marked in red but seams weird to me.

Could be useful to know the installation steps.

Thx :)

**Comment by raix** [comment] 2016-05-06 13:46
oh - there might be issues with the typescript/meteor import syntax - not sure if it's actually working.

the latest ground db is not using SQLite - it should add the npm version of localstorage however. [ref](https://github.com/GroundMeteor/db/blob/grounddb-caching-2016/package.js#L9)

**Comment by dagatsoin** [comment] 2016-05-06 14:08
You mean it does not use SQLite "directly"?
But it is faisable ifI use `localforage-cordovasqlitedriver`?

**Comment by dagatsoin** [comment] 2016-05-07 12:09
What is the best approach to abstract Mongo.collection and Ground.collection?
For exemple if I want to use an entities collection in offline or online case. Do I need to handle offlineEntities.find() and onlineEntities.find() depending if the user is offline or not?

**Comment by der-ede** [comment] 2016-06-18 09:25
Hi @raix 

thank you again for the package.
Since MDG recommends the usage of Method calls instead of inserting/updating minimongo on the client  one would probably need to reimplement the chunks from the old version of Ground:DB.
In my app we do not use callbacks anymore, because of the odd behavior of callbacks getting called only on reconnecting leading to an unpredictable state.
But this can be worked around. 

All in all it seems like every app/usecase is a little different which makes custom implementations necessary anyway I guess.

But with the codebase you provide for it should be doable to create an app with offline support/syncing on reconnect and SQLite storage on Cordova I suppose, only takes some time and effort to put into.

**Comment by ecerroni** [comment] 2016-06-18 11:26
Yep, resume of methods is very needed and it was what made V1 stand out, I mean perfect.

**Comment by der-ede** [comment] 2016-06-18 11:46
I was also thinking to just change the meteor call function a little bit so
it just checks whether status is connected and then decides to run the
callback function right after the client side method stub call or waits for
the server or maybe just waits some seconds for the server.
Then we could just take the code chunk with the method of version 0.3 and
apply it to v2 with a little adaption of code this should be possible.


Am Samstag, 18. Juni 2016 schrieb ric0 :

**Comment by der-ede** [comment] 2016-07-01 09:03
Hi @raix ,

ok , I get the idea of Ground:DB II, maybe that would make it easier to implement something like offline storage for React/GraphQL, more decoupled and adaptable.
But it also makes the interface a little more complex.

Would it be possible to have a sample/demo app or some more documentation then so we can understand the new functionality and implement it into our apps?


Regards

**Comment by raix** [comment] 2016-07-01 11:43
@der-ede I'm not sure, theres already a nice implementation for redux https://github.com/rt2zz/redux-persist

At the moment I'm holding back just a bit on Meteor and GraphQL

**Comment by dagatsoin** [comment] 2016-07-31 21:36
Hi @raix 
I wonder if it is still possible to watch the Meteor.user() and keep it offline.
I did:
```
    export const GUser = new GroundCollection('user');

    GUser.observeSource(Meteor.users.findOne(Meteor.userId()));

```
But I have errors:
```
Exception in onLogin callback: TypeError: source.find is not a function
    at GroundCollection.observeSource (http://localhost:3000/packages/ground_db.js?hash=bc8ae55d470c7d2e1ee35f4648843a9e00419508:333:83)
    at http://localhost:3000/app/app.js?hash=02dc6c704b922bb5297e8c71d239f4cd1e743d97:791:27
    at runAndHandleExceptions (http://localhost:3000/packages/callback-hook.js?hash=fff7fdef0707c85900b21f766a4b6c65bf278ff4:162:24)
    at http://localhost:3000/packages/callback-hook.js?hash=fff7fdef0707c85900b21f766a4b6c65bf278ff4:169:12
    at http://localhost:3000/packages/accounts-base.js?hash=93b4e125b77b1eebf232c67314f674ce3d15f389:313:9
    at Hook.each (http://localhost:3000/packages/callback-hook.js?hash=fff7fdef0707c85900b21f766a4b6c65bf278ff4:138:15)
    at http://localhost:3000/packages/accounts-base.js?hash=93b4e125b77b1eebf232c67314f674ce3d15f389:312:25
    at http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:794:19
    at loggedInAndDataReadyCallback (http://localhost:3000/packages/accounts-base.js?hash=93b4e125b77b1eebf232c67314f674ce3d15f389:434:5)
    at MethodInvoker._callback (http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:1105:22)
```

**Comment by raix** [comment] 2016-08-01 05:58
@dagatsoin I think you might have to hijack the Meteor.users collection on the client, eg.:
```js
  export const GUser = new GroundCollection('user');
  GUser.observeSource(Meteor.users.find());
  Meteor.users.find = function(args...) {
    return GUser.find(...args);
  }
```

**Comment by dagatsoin** [comment] 2016-08-01 07:30
No, ever tries bit as as I log into:
```
Exception in delivering result of invoking 'login': MinimongoError: Modifier must be an object
    at MinimongoError (http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:82:11)
    at Function.LocalCollection._modify (http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:3100:11)
    at LocalCollection.update (http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:818:21)
    at LocalCollection.upsert (http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:855:15)
    at GroundCollection.upsert (http://localhost:3000/packages/ground_db.js?hash=bc8ae55d470c7d2e1ee35f4648843a9e00419508:644:61)
    at MeteorAccount.autoSaveUser (http://localhost:3000/app/app.js?hash=0ea2778e63f85ccc27ea0cd53c04c56b50c314fb:951:28)
    at http://localhost:3000/app/app.js?hash=0ea2778e63f85ccc27ea0cd53c04c56b50c314fb:919:27
    at userCallback (http://localhost:3000/packages/accounts-password.js?hash=26c5712042d53cb92bed4571735603904d1ec8bd:96:23)
    at http://localhost:3000/packages/accounts-base.js?hash=93b4e125b77b1eebf232c67314f674ce3d15f389:322:26
    at http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:794:19
```

Or when I want to just keeping the current user with 
```
Accounts.onLogin(()=> {
  GUser.keep(Meteor.users.findOne(Meteor.userId()));
});
```

I get
```
Exception in onLogin callback: TypeError: Cannot read property 'map' of undefined
    at http://localhost:3000/packages/ground_db.js?hash=bc8ae55d470c7d2e1ee35f4648843a9e00419508:454:22
    at Array.map (native)
    at Function._.map._.collect (http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:167:56)
    at GroundCollection.keep (http://localhost:3000/packages/ground_db.js?hash=bc8ae55d470c7d2e1ee35f4648843a9e00419508:453:33)
    at http://localhost:3000/app/app.js?hash=fc1fa9b1adbe20fb82bdfc1c8450121e49514b1c:799:19
    at runAndHandleExceptions (http://localhost:3000/packages/callback-hook.js?hash=fff7fdef0707c85900b21f766a4b6c65bf278ff4:162:24)
    at http://localhost:3000/packages/callback-hook.js?hash=fff7fdef0707c85900b21f766a4b6c65bf278ff4:169:12
    at http://localhost:3000/packages/accounts-base.js?hash=93b4e125b77b1eebf232c67314f674ce3d15f389:313:9
    at Hook.each (http://localhost:3000/packages/callback-hook.js?hash=fff7fdef0707c85900b21f766a4b6c65bf278ff4:138:15)
    at http://localhost:3000/packages/accounts-base.js?hash=93b4e125b77b1eebf232c67314f674ce3d15f389:312:25
account.service.ts:75 METEOR USERID CHANGED rSBkx5hNdxDyhoMga
debug.js:41 Exception in onLogin callback: TypeError: Cannot read property 'map' of undefined
    at http://localhost:3000/packages/ground_db.js?hash=bc8ae55d470c7d2e1ee35f4648843a9e00419508:454:22
    at Array.map (native)
    at Function._.map._.collect (http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:167:56)
    at GroundCollection.keep (http://localhost:3000/packages/ground_db.js?hash=bc8ae55d470c7d2e1ee35f4648843a9e00419508:453:33)
    at http://localhost:3000/app/app.js?hash=fc1fa9b1adbe20fb82bdfc1c8450121e49514b1c:799:19
    at runAndHandleExceptions (http://localhost:3000/packages/callback-hook.js?hash=fff7fdef0707c85900b21f766a4b6c65bf278ff4:162:24)
    at http://localhost:3000/packages/callback-hook.js?hash=fff7fdef0707c85900b21f766a4b6c65bf278ff4:169:12
    at http://localhost:3000/packages/accounts-base.js?hash=93b4e125b77b1eebf232c67314f674ce3d15f389:313:9
    at Hook.each (http://localhost:3000/packages/callback-hook.js?hash=fff7fdef0707c85900b21f766a4b6c65bf278ff4:138:15)
    at http://localhost:3000/packages/accounts-base.js?hash=93b4e125b77b1eebf232c67314f674ce3d15f389:312:25
debug.js:41 Exception in delivering result of invoking 'login': MinimongoError: Modifier must be an object
    at MinimongoError (http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:82:11)
    at Function.LocalCollection._modify (http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:3100:11)
    at LocalCollection.update (http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:818:21)
    at LocalCollection.upsert (http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:855:15)
    at GroundCollection.upsert (http://localhost:3000/packages/ground_db.js?hash=bc8ae55d470c7d2e1ee35f4648843a9e00419508:644:61)
    at MeteorAccount.autoSaveUser (http://localhost:3000/app/app.js?hash=fc1fa9b1adbe20fb82bdfc1c8450121e49514b1c:954:28)
    at http://localhost:3000/app/app.js?hash=fc1fa9b1adbe20fb82bdfc1c8450121e49514b1c:922:27
    at userCallback (http://localhost:3000/packages/accounts-password.js?hash=26c5712042d53cb92bed4571735603904d1ec8bd:96:23)
    at http://localhost:3000/packages/accounts-base.js?hash=93b4e125b77b1eebf232c67314f674ce3d15f389:322:26
    at http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:794:19
```

**Comment by NitroBAY** [comment] 2016-08-29 21:02
Personally meteor.user can be grounded (tough the doc would gain to be more clear about keep/observeSource etc.)

**Comment by NitroBAY** [comment] 2016-11-06 17:57
@raix why do you say

> V1 listens to the localstorage events making updates in one tab also update in other tabs even if the app is offline, it's a feature that might be implemented in V2 later

> This version of GroundDB is a caching only storage - meaning it does not support resuming of method calls/cross tab updates etc.
This version of GroundDB is a caching only storage - meaning it does not support resuming of method calls/cross tab updates etc.

Actually when I make changes in a tab, reactivity makes that my other tab are updated accordingly to the changes I made from one tab. When I read you first, I've been thinking that when an user make a change in one tab, others tabs would keep an old, not updated accordingly to the other tab, version but it's not the case.

**Comment by NitroBAY** [comment] 2016-11-10 10:17
@raix can you explain why do you say that there's no sync between tabs, we're some to be confused

**Comment by raix** [comment] 2016-11-11 17:21
If you disconnect the server tab updates will stop working

**Comment by NitroBAY** [comment] 2016-11-11 17:35
:O really. I'm sorry but this is very very disappointing, this is one of the principle core of Meteor. I hope it's not very complex so one (maybe you @raix) can do it one day +1

**Comment by raix** [comment] 2016-11-12 06:20
what do you mean by "core principle" of Meteor?

**Comment by NitroBAY** [comment] 2016-11-12 06:44
This is one thing that is something in the core of Meteor and that I seen in the advantages of Meteor when I first  start off.

**Comment by dagatsoin** [comment] 2016-11-12 09:41
The behavior you described is not related with data persistence. It is related to network.
Having two tabs opened is like having two smartphones connecting to the same server. So if your server stops your smartphones also stops to be in sync. No matter If you use Meteor with/out ground collection. And this is the same for tabs.

**Comment by NitroBAY** [comment] 2016-11-12 11:16
In anyway as methods doesn't work offline when tab are needed to be synced ?

**Comment by der-ede** [comment] 2016-11-12 11:37
sorry to ask, but what is it with the tabs?
usually users/customers only have one tab open. 
if you want to test different users and the synchronization between them i'd recommend just opening one tab in two different browsers so you can be sure not to sync just the internal local storage but that the syncing is done through the server.

**Comment by NitroBAY** [comment] 2016-11-12 14:17
In my website people will be likely to have multiple tabs open.

**Comment by der-ede** [comment] 2016-11-12 14:33
@nitrobay: I was just thinking whether I open multiple tabs on a site and actually I do, but only on google search and on my cloud bookkeeping software, in the second case of which this could be omitted if the service was programmed better.
One other principle of meteor is to serve for the 90-95% of use cases. In special cases you probably would have to roll your own (based on grounddb).
Especially testing and trying out the behavior of the local storage. Do the different tabs all write into one local storage or separate and how can this be controlled? I mean you surely don't want to have unpredictable behavior of different instances writing simultaneously into the local storage.
Does the grounddb demo function on different tabs?

**Comment by NitroBAY** [comment] 2016-11-12 15:08
Yeah I'll definitely test this use case

**Comment by btafel** [comment] 2017-11-09 14:35
Hi @dagatsoin any luck caching Meteor.user? Thanks

**Closed** 2024-06-17 17:50 UTC
Labels: question
